/**
 * Pipeline type definitions.
 *
 * These mirror the shapes in dashboard/src/types/metrics.ts. Once the
 * project has a shared package these can be unified.
 */

// ---------------------------------------------------------------------------
// Config
// ---------------------------------------------------------------------------

export interface DeprecatedComponentReplacement {
  component: string;
  package: string;
}

export interface DeprecatedComponentConfig {
  paths: string[];
  replacement?: DeprecatedComponentReplacement;
  _autoGenerated?: boolean;
}

export interface ProjectConfig {
  rootFolder: string;
  legacyComponentFolder?: string;
  ignoreFolders: string[];
  filePattern: string;
  outputFile: string;
  currentPackages: string[];
  currentComponents: string[];
  deprecatedComponents: Record<string, DeprecatedComponentConfig>;
  codeOwnerMetricIgnoreGlobs?: string[];
}

export interface Config {
  projects: Record<string, ProjectConfig>;
}

// ---------------------------------------------------------------------------
// Metrics outputs (written by index.js, read by pipeline)
// ---------------------------------------------------------------------------

export interface CodeOwnerStats {
  mmdsInstances: number;
  deprecatedInstances: number;
  totalInstances: number;
  migrationPercentage: string;
  filesCount: number;
}

export interface MetricsSummary {
  totalComponents: number;
  mmdsInstances: number;
  deprecatedInstances: number;
  totalInstances: number;
  migrationPercentage: string;
  fullyMigrated: number;
  inProgress: number;
  notStarted: number;
  codeOwnerStats?: Record<string, CodeOwnerStats>;
}

export interface ComponentData {
  replacementComponent: string;
  legacyComponents: string[];
  legacyInstances: number;
  mmdsInstances: number;
  totalInstances: number;
  migrationPercentage: string;
}

export interface MetricsData {
  project: string;
  date: string;
  generatedAt: string;
  mmdsComponentsAvailable: number;
  mmdsComponentsList: string[];
  newComponents: string[];
  summary: MetricsSummary;
  components: ComponentData[];
}

// ---------------------------------------------------------------------------
// Timeline
// ---------------------------------------------------------------------------

export interface CodeOwnerTimelineEntry {
  migrationPercentage: number[];
  mmdsInstances: number[];
  deprecatedInstances: number[];
  totalInstances: number[];
}

export interface CodeOwnerTimeline {
  dates: string[];
  owners: Record<string, CodeOwnerTimelineEntry>;
}

export interface LatestChange {
  migrationPercentageChange: string;
  mmdsInstancesChange: number;
  deprecatedInstancesChange: number;
  componentsFullyMigratedChange: number;
  componentsInProgressChange: number;
  mmdsComponentsAvailableChange: number;
}

export interface ProjectTimeline {
  dates: string[];
  migrationPercentage: number[];
  mmdsInstances: number[];
  deprecatedInstances: number[];
  totalInstances: number[];
  componentsFullyMigrated: number[];
  componentsInProgress: number[];
  componentsNotStarted: number[];
  totalComponents: number[];
  mmdsComponentsAvailable: number[];
  mmdsComponentsList: string[][];
  newComponents: string[][];
  codeOwnerTimeline: CodeOwnerTimeline;
  latestChange: LatestChange | null;
}

export interface TimelineData {
  generatedAt: string;
  mobile: ProjectTimeline;
  extension: ProjectTimeline;
  summary: {
    totalWeeks: number;
    dateRange: {
      start: string | null;
      end: string | null;
    };
  };
}

// ---------------------------------------------------------------------------
// Index
// ---------------------------------------------------------------------------

export interface IndexEntry {
  date: string;
  file: string;
}

export interface IndexData {
  lastUpdated: string;
  projects: {
    mobile: IndexEntry[];
    extension: IndexEntry[];
  };
  latest: {
    mobile: string | null;
    extension: string | null;
  };
}

// ---------------------------------------------------------------------------
// Pipeline internals
// ---------------------------------------------------------------------------

export type Project = 'mobile' | 'extension';

export interface ProjectDataEntry {
  date: string;
  file: string;
  data: MetricsData;
}

export interface AllProjectData {
  mobile: ProjectDataEntry[];
  extension: ProjectDataEntry[];
}
